# -*- coding: utf-8 -*-
"""Student Performance Linear regression .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QaQPiMrN0aCBhVQymPMSJGe920Mlluo5
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sn

df=pd.read_csv("/content/Student_Performance.csv")

df.head()

df.tail()

df.shape

df.describe()

df.info()

df.isna().sum()

## Graphical representation
sn.pairplot(df,x_vars=('Hours Studied', 'Previous Scores', 'Sleep Hours', 'Sample Question Papers Practiced'),y_vars=('Performance Index'),kind="scatter")

sn.pairplot(df,x_vars=('Hours Studied', 'Previous Scores','Sleep Hours', 'Sample Question Papers Practiced'),y_vars=('Performance Index'),kind="reg")

df.drop('Extracurricular Activities',axis=1,inplace=True)

df.corr()

sn.heatmap(df.corr(),annot=True)

df.columns

X=df[['Hours Studied', 'Previous Scores', 'Sleep Hours', 'Sample Question Papers Practiced']]
y=df['Performance Index']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

from sklearn.linear_model import LinearRegression
model=LinearRegression()

model.fit(X_train,y_train)

model.score(X_test,y_test)

predict=model.predict(X_test)
predict

# y=mx+c
model.intercept_

model.coef_

## mertics
# MAE
# MSE
# RMSE
# R2 and adjusted R2

from sklearn.metrics import mean_absolute_error
mae=mean_absolute_error(y_test,predict)
mae

from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,predict)
mse

rmse = np.sqrt(mse)
rmse

import math
math.sqrt(mean_squared_error(y_test,predict))

import statsmodels.api as sm

X12=sm.add_constant(X)
X12

fit12=sm.OLS(y,X12).fit()

print(fit12.summary())